using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Partivex.Infrastructure.Data;

#nullable disable

namespace Partivex.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260428000000_AddVendorTable")]
    public partial class AddVendorTable : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "Vendors" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "Name" text NOT NULL,
                    "ContactPerson" text NOT NULL,
                    "Email" text NOT NULL,
                    "Phone" text NOT NULL,
                    "Address" text NOT NULL,
                    "IsActive" boolean NOT NULL,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    CONSTRAINT "PK_Vendors" PRIMARY KEY ("Id")
                );
                """);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""DROP TABLE IF EXISTS "Vendors";""");
        }
    }
}
